import type { Metadata } from "next";
import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";
import { QueryProvider } from "@/components/query-provider";
import Header from "@/components/header";
import { getSiteSettings } from "@/lib/get-site-settings";

const geist = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const settings = await getSiteSettings()

  return (
    <html lang="en">
      <body className={`${geist.variable} ${geistMono.variable} bg-background text-foreground antialiase dark pt-20`}>
        <Header settings={settings} />
        <QueryProvider>
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
